"""Shared task prompts, used by both coordination topologies.

The federated pipeline (agents/*.py, one crew per agent) and the unified crew
(agents/crew_pipeline.py, one crew for all agents) must issue the SAME
instructions, or a measured difference between them is attributable to prompt
wording rather than to coordination topology -- which would make the comparison
meaningless. These builders are the single source of truth.

Each builder takes the upstream artifacts as an already-formatted string. The
two topologies differ only in what they pass:

    federated:  json.dumps(requirements, indent=2)   -- the artifact inline
    unified:    UPSTREAM_FROM_CONTEXT                -- a pointer to task context

That substitution is the ONLY intended difference between conditions, and it is
unavoidable: a unified crew propagates prior output through ``context`` rather
than through string interpolation. Section "Threats to Validity" should say so.
"""
from __future__ import annotations

#: Passed by the unified crew in place of an inline artifact. CrewAI injects the
#: real upstream output through the task's ``context``, so the prompt only needs
#: to name which artifact it should look for.
UPSTREAM_FROM_CONTEXT = (
    "(provided in this task's context, as the output of the preceding task)"
)


# ---------------------------------------------------------------------------
# Requirements Analyst
# ---------------------------------------------------------------------------

REQUIREMENTS_SYSTEM_PROMPT = """You are an expert software requirements analyst. Your ONLY job is to output a compact JSON object. NEVER write explanations, questions, or prose.

Output ONLY a JSON object with this structure (start with {, end with }):

{
  "project_name": "string",
  "features": [
    {
      "id": "F1",
      "name": "string",
      "description": "one sentence",
      "priority": "High",
      "user_stories": ["As a <role>, I can <action> so that <benefit>."],
      "acceptance_criteria": ["Given <context>, When <action>, Then <result>."]
    }
  ],
  "technical_requirements": {
    "platform": ["Web"],
    "technologies": ["string"],
    "database": "PostgreSQL"
  },
  "user_roles": ["string"]
}

STRICT RULES:
1. Output ONLY the JSON object. No markdown. No ```json. No text before or after.
2. Start with { and end with }.
3. Include 3 to 5 features. Each feature: exactly 2 user_stories and 2 acceptance_criteria. Keep every string under 150 characters.
4. Feature IDs: F1, F2, F3... Priorities: High, Medium, or Low only.
5. Do NOT include a database_schema key — that is generated by a separate agent.
6. If information is missing, make a reasonable assumption — never ask questions."""


def build_requirements_prompt(user_input: str) -> str:
    """Full requirements task description, including the user's project idea."""
    return (
        f"{REQUIREMENTS_SYSTEM_PROMPT}\n\n"
        "User input (chat transcript):\n"
        f"{user_input}\n\n"
        "Return ONLY the JSON object."
    )


# ---------------------------------------------------------------------------
# Database Agent
# ---------------------------------------------------------------------------

def build_database_prompt(req_json: str) -> str:
    return f"""From these requirements, produce a complete database schema. Rules:
- Use snake_case for all table and column names.
- Every table must have exactly one primary key column.
- Explicitly define foreign key columns (e.g. user_id) and list them in the relationships array with fk/ref fields.
- Add junction tables for many-to-many relationships.
- Output ONLY a flat JSON object (no wrapper key) with no markdown.

REQUIREMENTS:
{req_json}

Output JSON structure exactly:
{{
  "tables": [
    {{
      "name": "table_name",
      "purpose": "...",
      "columns": [{{"name": "id", "type": "uuid", "pk": true, "nullable": false, "unique": false, "default": null, "notes": null}}],
      "indexes": ["col_name"],
      "relationships": [{{"type": "many-to-one", "to_table": "other", "fk": "other_id", "ref": "id", "notes": null}}]
    }}
  ],
  "assumptions": ["..."]
}}"""


# ---------------------------------------------------------------------------
# Planning Manager
# ---------------------------------------------------------------------------

def build_planning_prompt(req_json: str, design_json: str) -> str:
    return f"""Create a short-term MVP execution plan. Output ONLY a JSON object with no markdown.

REQUIREMENTS:
{req_json}

DESIGN:
{design_json}

Output JSON with:
- plan_name: e.g. "MVP Plan"
- tasks: AT LEAST 5-8 items, each with id, title, assigned_agent (Developer/Designer/DBA), priority (high or low)
- risks: 3-5 short risk strings"""


# ---------------------------------------------------------------------------
# Quality / Process Manager
# ---------------------------------------------------------------------------

def build_quality_prompt(req_json: str, design_json: str, db_json: str) -> str:
    return f"""Inspect these artifacts and produce a quality gate report. Output ONLY a JSON object with no markdown.

REQUIREMENTS:
{req_json}

DESIGN:
{design_json}

DATABASE SCHEMA:
{db_json}

Output JSON with:
- gate_decision: "PASS" or "FAIL"
- artifact_reviewed: list of strings e.g. ["Requirements", "Design", "Database"]
- checklist: object with boolean fields: requirements_complete, design_consistent, db_matches_requirements, nfr_defined
- issues: list of objects with severity (High/Medium/Low), item, message
- required_fixes: list of strings
- recommendations: list of strings (at least 2-3)"""


# ---------------------------------------------------------------------------
# Support Manager
# ---------------------------------------------------------------------------

def build_support_prompt(req_json: str, design_json: str, db_json: str, plan_json: str) -> str:
    return f"""Produce a support governance package from these project artifacts. Output ONLY a JSON object with no markdown.

REQUIREMENTS:
{req_json}

DESIGN:
{design_json}

DATABASE SCHEMA:
{db_json}

CYCLE PLAN:
{plan_json}

Output JSON with:
- app_documentation: 2-4 paragraph string describing the app being built (what it is, main purpose, main features, intended users)
- baseline_artifacts: list of at least 3 strings e.g. ["Requirements_v1", "Design_v1", "Database_v1"]
- glossary: object mapping 4-6 terms to their definitions"""
