import os
import time
import requests
from typing import Dict, Any

import streamlit as st

from core.constants import (
    DEFAULT_MODEL, MAX_RETRIES, MAX_ITERATIONS, MAX_EXECUTION_TIME,
    ERROR_NO_API_KEY, SOLUTION_ADD_API_KEY,
)
from core.models import PYDANTIC_AVAILABLE, RequirementsOutputModel
from core.llm import CREWAI_AVAILABLE, Agent, Task, Crew, Process, get_llm
from core.utils import parse_json_from_text, extract_crewai_output
from utils.io_suppression import suppress_stderr, suppress_io


def _anthropic_text_from_messages_api(data: dict) -> str:
    """Join all `text` blocks from a Messages API JSON response."""
    parts: list[str] = []
    for block in data.get("content") or []:
        if isinstance(block, dict) and block.get("type") == "text":
            t = block.get("text")
            if isinstance(t, str) and t.strip():
                parts.append(t)
    return "\n".join(parts).strip()


class RequirementsAnalystAgent:
    """Agent responsible for analyzing and structuring software requirements using CrewAI."""
    
    def __init__(self) -> None:
        self.api_key = os.getenv("ANTHROPIC_API_KEY")
        # Initialize attributes to None first
        self.agent = None
        self.crew = None
        self.task = None

        # Setup for direct API calls
        self.api_base = "https://api.anthropic.com/v1"
        self.headers = {
            "x-api-key": self.api_key,
            "anthropic-version": "2023-06-01",
            "Content-Type": "application/json",
        } if self.api_key else {}
        
        self.system_prompt = """You are an expert software requirements analyst. Your ONLY job is to output a compact JSON object. NEVER write explanations, questions, or prose.

Output ONLY a JSON object with this structure (start with {, end with }):

{
  "project_name": "string",
  "features": [
    {
      "id": "F1",
      "name": "string",
      "description": "one sentence",
      "priority": "High",
      "user_stories": ["As a <role>, I can <action> so that <benefit>."],
      "acceptance_criteria": ["Given <context>, When <action>, Then <result>."]
    }
  ],
  "technical_requirements": {
    "platform": ["Web"],
    "technologies": ["string"],
    "database": "PostgreSQL"
  },
  "user_roles": ["string"]
}

STRICT RULES:
1. Output ONLY the JSON object. No markdown. No ```json. No text before or after.
2. Start with { and end with }.
3. Include 3 to 5 features. Each feature: exactly 2 user_stories and 2 acceptance_criteria. Keep every string under 150 characters.
4. Feature IDs: F1, F2, F3... Priorities: High, Medium, or Low only.
5. Do NOT include a database_schema key — that is generated by a separate agent.
6. If information is missing, make a reasonable assumption — never ask questions."""
        
        if not CREWAI_AVAILABLE:
            return
    
        llm = get_llm()
        
        # Create CrewAI agent (will use ANTHROPIC_API_KEY from env if llm is None)
        agent_kwargs = {
            "role": "Software Requirements Analyst",
            "goal": "Analyze user requirements and OUTPUT a complete JSON object with features, technical requirements, and user roles. You must produce the actual JSON output, not just think about it.",
            "backstory": """You are an expert software requirements analyst with years of experience 
            in breaking down complex ideas into structured, actionable requirements. You excel at 
            identifying features, prioritizing them, and creating comprehensive technical specifications.
            You always produce complete, valid JSON outputs without unnecessary explanations.""",
            "verbose": False,
            "allow_delegation": False,
            "max_iter": MAX_ITERATIONS,
            "max_execution_time": MAX_EXECUTION_TIME,
        }
        if llm:
            agent_kwargs["llm"] = llm
        
        try:
            from utils.io_suppression import suppress_stderr
            with suppress_stderr():
                self.agent = Agent(**agent_kwargs)
        except Exception as e:
            error_msg = str(e)
            if "signal" not in error_msg.lower() and "telemetry" not in error_msg.lower():
                st.error(f"Failed to create CrewAI agent: {e}")
            self.agent = None
            self.crew = None
            return
        
        # Create task with explicit output requirements.
        # Use Pydantic model for output_json if available, otherwise rely on expected_output description.
        task_kwargs = {
            "description": self.system_prompt,
            "agent": self.agent,
            "expected_output": (
                "A complete, valid JSON object starting with { and ending with }, containing: "
                "project_name, features, technical_requirements, user_roles, and database_schema. "
                "No markdown, no explanations, only JSON."
            ),
        }
        
        # Add output_json if Pydantic is available
        if PYDANTIC_AVAILABLE and RequirementsOutputModel:
            task_kwargs["output_json"] = RequirementsOutputModel
        
        self.task = Task(**task_kwargs)
        
        # Create crew (suppress telemetry errors)
        try:
            from utils.io_suppression import suppress_stderr
            with suppress_stderr():
                self.crew = Crew(
                    agents=[self.agent],
                    tasks=[self.task],
                    verbose=False,
                    process=Process.sequential,
                )
        except Exception as e:
            error_msg = str(e)
            if "signal" not in error_msg.lower() and "telemetry" not in error_msg.lower():
                st.error(f"Failed to create CrewAI crew: {e}")
            self.crew = None

    def analyze_requirements(self, user_input: str, max_retries: int = 3) -> Dict[str, Any]:
        """Analyze user requirements and return structured JSON."""
        if not self.api_key:
            return {
                "error": "Anthropic API key not found",
                "solution": "Add ANTHROPIC_API_KEY to your .env file",
            }

        # 1) Try CrewAI first — full orchestration with role, goal, and backstory context
        if CREWAI_AVAILABLE and self.crew and self.task:
            try:
                self.task.description = (
                    f"{self.system_prompt}\n\n"
                    "User input (chat transcript):\n"
                    f"{user_input}\n\n"
                    "Return ONLY the JSON object."
                )
                from utils.io_suppression import suppress_io
                with suppress_io():
                    result = self.crew.kickoff(inputs={"user_input": user_input})

                if hasattr(result, "tasks_output") and result.tasks_output:
                    task_out = result.tasks_output[0]
                    if hasattr(task_out, "json_dict") and isinstance(task_out.json_dict, dict):
                        parsed = task_out.json_dict
                        parsed["model_used"] = "CrewAI"
                        parsed["timestamp"] = time.strftime("%Y-%m-%d %H:%M:%S")
                        return parsed
                    if hasattr(task_out, "json") and isinstance(task_out.json, dict):
                        parsed = task_out.json
                        parsed["model_used"] = "CrewAI"
                        parsed["timestamp"] = time.strftime("%Y-%m-%d %H:%M:%S")
                        return parsed

                content = extract_crewai_output(result)
                if content:
                    parsed = parse_json_from_text(content)
                    if isinstance(parsed, dict) and "error" not in parsed:
                        parsed["model_used"] = "CrewAI"
                        parsed["timestamp"] = time.strftime("%Y-%m-%d %H:%M:%S")
                        return parsed
            except Exception:
                pass

        # 2) Fallback: direct Anthropic API if CrewAI unavailable or failed
        for attempt in range(max_retries):
            try:
                # No spinner here: the caller already displays one, and a nested
                # st.spinner renders a second identical message. Progress display
                # belongs to the UI layer, not to the agent.
                resp = requests.post(
                    f"{self.api_base}/messages",
                    headers=self.headers,
                    json={
                        "model": DEFAULT_MODEL,
                        "max_tokens": 8192,
                        "system": self.system_prompt,
                        "messages": [
                            {
                                "role": "user",
                                "content": (
                                    f"{user_input}\n\n"
                                    "IMPORTANT: Output ONLY the JSON object described in your instructions. "
                                    "Do not write any text, explanation, or questions. Start with { and end with }."
                                ),
                            },
                        ],
                    },
                    timeout=90,
                )

                if resp.status_code == 401:
                    return {
                        "error": "Authentication failed",
                        "raw_error": resp.text,
                        "solution": "Check ANTHROPIC_API_KEY in your .env file",
                    }

                if resp.status_code != 200:
                    if attempt < max_retries - 1:
                        time.sleep(2)
                        continue
                    return {
                        "error": f"Anthropic API HTTP {resp.status_code}",
                        "raw_error": resp.text[:8000],
                        "solution": "Check model name (DEFAULT_MODEL), quota, and Anthropic status.",
                    }

                data = resp.json()
                content = _anthropic_text_from_messages_api(data)
                if not content:
                    if attempt < max_retries - 1:
                        time.sleep(2)
                        continue
                    return {
                        "error": "Empty response from Anthropic",
                        "solution": "Retry analysis or check DEFAULT_MODEL and API response format.",
                        "raw_error": str(data)[:2000],
                    }

                parsed = parse_json_from_text(content)
                if isinstance(parsed, dict) and "error" not in parsed:
                    parsed["model_used"] = DEFAULT_MODEL
                    parsed["timestamp"] = time.strftime("%Y-%m-%d %H:%M:%S")
                    return parsed

                return {
                    "error": "Model returned text instead of requirements JSON",
                    "solution": (
                        "Anthropic responded successfully, but not with the expected JSON object. "
                        "If you were still in conversational mode, continue the chat first, then run "
                        "structured analysis again. Otherwise retry or tighten DEFAULT_MODEL / prompts."
                    ),
                    "parse_error": parsed.get("error") if isinstance(parsed, dict) else str(parsed),
                    "raw_response": content[:8000],
                }

            except requests.exceptions.Timeout:
                if attempt < max_retries - 1:
                    st.warning("Timeout. Retrying…")
                    time.sleep(2)
                    continue
                return {"error": "Request timeout. Please try again."}
            except Exception as e:
                if attempt < max_retries - 1:
                    st.warning(f"Error: {e}. Retrying…")
                    time.sleep(2)
                    continue
                return {"error": f"Unexpected error: {e}"}

        return {"error": "Max retries exceeded"}


# ----------------------------
# DESIGN AGENT (CrewAI)
# ----------------------------
